### ISSUE TITLE
kafka_advertised_listeners is not resolved

### ISSUE THREAD

**Issue by DawidNiezgodka** [sleighzy/ansible-kafka#35]
I want to set up `advertised.listeners`, but the value won't resolve. Even though the variable is set in the config, one can see the following: 
`#advertised.listeners=PLAINTEXT://your.host.name:9092`

Here's the complete playbook:
```
- name: Install openjdk-8-jdk on all nodes
  hosts: kafka-nodes
  become: true
  tasks:
    - name: Install openjdk-8-jdk
      apt:
        name: openjdk-8-jdk
        state: present
        update_cache: yes

- name: Setup zookeeper
  hosts: kafka-nodes
  roles:
    - role: sleighzy.zookeeper
  vars:
      zookeeper_servers:
        - kafka1

      zookeeper_mirror: https://archive.apache.org/dist/zookeeper
      zookeeper_version: 3.6.4
      zookeeper_package: apache-zookeeper-3.6.4-bin.tar.gz
      zookeeper_servers_use_inventory_hostname: true

- name: Setup kafka
  hosts: kafka-nodes
  become: true
  roles:
    - role: sleighzy.kafka
  vars:
    kafka_download_base_url: https://archive.apache.org/dist/kafka
    kafka_broker_id: "{{ inventory_hostname.split('kafka')[-1] }}"
    kafka_advertised_listeners: "[\"PLAINTEXT://{{ansible_ssh_host}}:9092\"]"
    kafka_version: 2.7.0
    kafka_scala_version: 2.13
```

The way the value is passed seems correct. When I run the following task, it gives me the value correctly:
```
- name: Print kafka_advertised_listeners value
  hosts: kafka-nodes
  tasks:
    - name: Print value
      debug:
        msg: "[\"PLAINTEXT://{{ansible_ssh_host}}:9092\"]"
```
->
```

        ok: [kafka1] => {
    "msg": [
        "PLAINTEXT://1.2.3.4:9092"
    ]
}
```

**Comment by sleighzy** [comment]
Hi @DawidNiezgodka . It looks like you may be providing this value as a string vs. an array. For example, you have the following:

```
kafka_advertised_listeners: "[\"PLAINTEXT://{{ansible_ssh_host}}:9092\"]"
```

This Ansible role takes an array and then joins the entries using commas. https://github.com/sleighzy/ansible-kafka/blob/master/templates/server.properties.j2#L54

Could you try something like the below instead and see if this works for you:

```
kafka_advertised_listeners:
  - PLAINTEXT://{{ansible_ssh_host}}:9092
 ```

**Comment by DawidNiezgodka** [comment]
Thanks for the quick reply.

Hmm, it does not work.
I tried both:
1. Without quotes: `- PLAINTEXT://{{ansible_ssh_host}}:9092`
2. With quotes `"PLAINTEXT://{{ansible_ssh_host}}:9092"`

Indentation seems correct, i.e., space, space, -, space, `PLA...`

The workaround I found is to set `kafka_start: no`, and then:

```
- name: Add advertised.listeners to server.properties
  hosts: kafka-nodes
  tasks:
    - name: Add advertised.listeners line
      lineinfile:
        path: /etc/kafka/server.properties
        line: "advertised.listeners=PLAINTEXT://{{ansible_ssh_host}}:9092"
        create: no

    - name: Start kafka service
      service:
        name: kafka
        state: started
        enabled: yes
```
However, I'd be happy to find the culprit and use it directly ;)
